apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: vncmqttbridges.utilities.strudelline.net
spec:
  group: utilities.strudelline.net
  names:
    kind: VNCMQTTBridge
    listKind: VNCMQTTBridgeList
    plural: vncmqttbridges
    singular: vncmqttbridge
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: VNCMQTTBridge is the Schema for the vncmqttbridges API
        properties:
          apiVersion: {"description": "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources","type":"string"}
          kind: {"description":"Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds","type":"string"}
          metadata: {"type":"object"}
          spec:
            description: VNCMQTTBridgeSpec defines the desired state of VNCMQTTBridge
            properties:
              image: {"type": "string"}
              deviceId: {"type": "string"}
              deviceName: {"type": "string"}
              interval: {"type": "string"}
              vncSecretName:
                type: string
                description: |-
                  Secret which contains the VNC host and password
              mqttSecretName:
                type: string
                description: |-
                  Secret which contains the MQTT host, username, and password
              commonAnnotations:
                type: object
                additionalProperties: true
            required:
            - deviceName
            - vncSecretName
            - mqttSecretName
            type: object
        required:
        - spec
        type: object
    served: true
    storage: true
    subresources:
      status: {}
